#!/usr/bin/env python3

from sys import argv
from pathlib import Path

directory = argv[1]
oldpattern = argv[2]
newpattern = argv[3]

# from traverse.py
def print_path(path):
	print(str(path.absolute()))
	if path.is_dir():
		for entry in path.iterdir():
			print_path(entry)
print_path(Path(directory))
